#############################################################################
# Makefile for building: paintTest
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? 12? 30 15:51:17 2009
# Project:  paintTest.pro
# Template: app
# Command: /home/student/qtsdk-2009.05/qt/bin/qmake -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile paintTest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -I. -I../../qtsdk-2009.05/qt/include/QtCore -I../../qtsdk-2009.05/qt/include/QtGui -I../../qtsdk-2009.05/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/student/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/student/qtsdk-2009.05/qt/lib -lQtGui -L/home/student/qtsdk-2009.05/qt/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/student/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mywidget.cpp \
		openfile.cpp \
		combinefiles.cpp \
		option.cpp \
		help.cpp moc_mainwindow.cpp \
		moc_mywidget.cpp \
		moc_openfile.cpp \
		moc_combinefiles.cpp \
		moc_option.cpp \
		moc_help.cpp \
		qrc_image.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mywidget.o \
		openfile.o \
		combinefiles.o \
		option.o \
		help.o \
		moc_mainwindow.o \
		moc_mywidget.o \
		moc_openfile.o \
		moc_combinefiles.o \
		moc_option.o \
		moc_help.o \
		qrc_image.o
DIST          = ../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		paintTest.pro
QMAKE_TARGET  = paintTest
DESTDIR       = 
TARGET        = paintTest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_openfile.h ui_combinefiles.h ui_option.h ui_help.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: paintTest.pro  ../../qtsdk-2009.05/qt/mkspecs/linux-g++-64/qmake.conf ../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/home/student/qtsdk-2009.05/qt/lib/libQtGui.prl \
		/home/student/qtsdk-2009.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile paintTest.pro
../../qtsdk-2009.05/qt/mkspecs/common/g++.conf:
../../qtsdk-2009.05/qt/mkspecs/common/unix.conf:
../../qtsdk-2009.05/qt/mkspecs/common/linux.conf:
../../qtsdk-2009.05/qt/mkspecs/qconfig.pri:
../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2009.05/qt/mkspecs/features/debug.prf:
../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2009.05/qt/mkspecs/features/qt.prf:
../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2009.05/qt/mkspecs/features/moc.prf:
../../qtsdk-2009.05/qt/mkspecs/features/resources.prf:
../../qtsdk-2009.05/qt/mkspecs/features/uic.prf:
../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
../../qtsdk-2009.05/qt/mkspecs/features/lex.prf:
../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/home/student/qtsdk-2009.05/qt/lib/libQtGui.prl:
/home/student/qtsdk-2009.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile paintTest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/paintTest1.0.0 || $(MKDIR) .tmp/paintTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/paintTest1.0.0/ && $(COPY_FILE) --parents mainwindow.h mywidget.h openfile.h combinefiles.h option.h help.h .tmp/paintTest1.0.0/ && $(COPY_FILE) --parents image.qrc .tmp/paintTest1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp mywidget.cpp openfile.cpp combinefiles.cpp option.cpp help.cpp .tmp/paintTest1.0.0/ && $(COPY_FILE) --parents mainwindow.ui openfile.ui combinefiles.ui option.ui help.ui .tmp/paintTest1.0.0/ && $(COPY_FILE) --parents paintTest_zh.ts paintTest_en.ts .tmp/paintTest1.0.0/ && (cd `dirname .tmp/paintTest1.0.0` && $(TAR) paintTest1.0.0.tar paintTest1.0.0 && $(COMPRESS) paintTest1.0.0.tar) && $(MOVE) `dirname .tmp/paintTest1.0.0`/paintTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/paintTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mywidget.cpp moc_openfile.cpp moc_combinefiles.cpp moc_option.cpp moc_help.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mywidget.cpp moc_openfile.cpp moc_combinefiles.cpp moc_option.cpp moc_help.cpp
moc_mainwindow.cpp: mywidget.h \
		option.h \
		ui_option.h \
		openfile.h \
		ui_openfile.h \
		combinefiles.h \
		ui_combinefiles.h \
		help.h \
		ui_help.h \
		mainwindow.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_mywidget.cpp: option.h \
		ui_option.h \
		mywidget.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o moc_mywidget.cpp

moc_openfile.cpp: ui_openfile.h \
		openfile.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) openfile.h -o moc_openfile.cpp

moc_combinefiles.cpp: ui_combinefiles.h \
		combinefiles.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) combinefiles.h -o moc_combinefiles.cpp

moc_option.cpp: ui_option.h \
		option.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) option.h -o moc_option.cpp

moc_help.cpp: ui_help.h \
		help.h
	/home/student/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) help.h -o moc_help.cpp

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		image/index_5.png \
		image/wheel.png \
		image/32px-Crystal_Clear_mimetype_source_r.png \
		image/gnome-stock-gnome-run.png \
		image/s.png \
		image/Torchlight_qt.png \
		image/index_6.png \
		image/120px-Torchlight_viewmag_plus.png \
		image/Crystal_Clear_action_button_cancel.png \
		image/rightclick.png \
		image/index_0.png \
		image/Nuvola_filesystems_folder_blue_open.png \
		image/index_7.png \
		image/32px-Crystal_Clear_app_database.png \
		image/receiveline.png \
		image/wrong.png \
		image/Nuvola_filesystems_folder_grey_open.png \
		image/index_1.png \
		image/32px-Crystal_Clear_action_db_remove.png \
		image/Crystal_Clear_action_exit.png \
		image/leftclick.png \
		image/index_2.png \
		image/fang.png \
		image/sr.png \
		image/32px-Crystal_Clear_action_viewmag-.png \
		image/32px-Crystal_Clear_action_db_add.png \
		image/index_3.png \
		image/Crystal_Clear_action_decrypted.png \
		image/plus.png \
		image/index_4.png \
		image/120px-Torchlight_viewmag_minus.png \
		image/Crystal_Clear_action_reload.png \
		image/32px-Crystal_Clear_action_viewmag+.png \
		image/Torchlight_help.png \
		image/Nuvola_filesystems_folder_yellow_open.png \
		image/r.png \
		image/32px-Crystal_Clear_action_db_update.png \
		image/Crystal_Clear_action_apply.png \
		image/edit-select-all.png
	/home/student/qtsdk-2009.05/qt/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_openfile.h ui_combinefiles.h ui_option.h ui_help.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_openfile.h ui_combinefiles.h ui_option.h ui_help.h
ui_mainwindow.h: mainwindow.ui
	/home/student/qtsdk-2009.05/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_openfile.h: openfile.ui
	/home/student/qtsdk-2009.05/qt/bin/uic openfile.ui -o ui_openfile.h

ui_combinefiles.h: combinefiles.ui
	/home/student/qtsdk-2009.05/qt/bin/uic combinefiles.ui -o ui_combinefiles.h

ui_option.h: option.ui
	/home/student/qtsdk-2009.05/qt/bin/uic option.ui -o ui_option.h

ui_help.h: help.ui
	/home/student/qtsdk-2009.05/qt/bin/uic help.ui -o ui_help.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mywidget.h \
		option.h \
		ui_option.h \
		openfile.h \
		ui_openfile.h \
		combinefiles.h \
		ui_combinefiles.h \
		help.h \
		ui_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mywidget.h \
		option.h \
		ui_option.h \
		openfile.h \
		ui_openfile.h \
		combinefiles.h \
		ui_combinefiles.h \
		help.h \
		ui_help.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mywidget.o: mywidget.cpp mywidget.h \
		option.h \
		ui_option.h \
		mainwindow.h \
		openfile.h \
		ui_openfile.h \
		combinefiles.h \
		ui_combinefiles.h \
		help.h \
		ui_help.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o mywidget.cpp

openfile.o: openfile.cpp openfile.h \
		ui_openfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openfile.o openfile.cpp

combinefiles.o: combinefiles.cpp combinefiles.h \
		ui_combinefiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o combinefiles.o combinefiles.cpp

option.o: option.cpp option.h \
		ui_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o option.o option.cpp

help.o: help.cpp help.h \
		ui_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o help.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_openfile.o: moc_openfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openfile.o moc_openfile.cpp

moc_combinefiles.o: moc_combinefiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_combinefiles.o moc_combinefiles.cpp

moc_option.o: moc_option.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_option.o moc_option.cpp

moc_help.o: moc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_help.o moc_help.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

