#############################################################################
# Makefile for building: SPSShow
# Generated by qmake (2.01a) (Qt 4.5.3) on: ?? 3? 22 14:39:53 2010
# Project:  qjdspsshow.pro
# Template: app
# Command: /home/student/qtsdk-2009.04/qt/bin/qmake -unix -o Makefile qjdspsshow.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I../../qtsdk-2009.04/qt/mkspecs/linux-g++-64 -I. -I../../qtsdk-2009.04/qt/include/QtCore -I../../qtsdk-2009.04/qt/include/QtGui -I../../qtsdk-2009.04/qt/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/student/qtsdk-2009.04/qt/lib
LIBS          = $(SUBLIBS)  -L/home/student/qtsdk-2009.04/qt/lib -lQtGui -L/home/student/qtsdk-2009.04/qt/lib -L/usr/X11R6/lib64 -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/student/qtsdk-2009.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qjd_sps_mainwindow.cpp \
		qjd_sps_widget.cpp \
		qjd_sps_openfile.cpp \
		qjd_sps_combinefiles.cpp \
		qjd_sps_option.cpp \
		qjd_sps_help.cpp moc_qjd_sps_mainwindow.cpp \
		moc_qjd_sps_widget.cpp \
		moc_qjd_sps_openfile.cpp \
		moc_qjd_sps_combinefiles.cpp \
		moc_qjd_sps_option.cpp \
		moc_qjd_sps_help.cpp \
		qrc_image.cpp
OBJECTS       = main.o \
		qjd_sps_mainwindow.o \
		qjd_sps_widget.o \
		qjd_sps_openfile.o \
		qjd_sps_combinefiles.o \
		qjd_sps_option.o \
		qjd_sps_help.o \
		moc_qjd_sps_mainwindow.o \
		moc_qjd_sps_widget.o \
		moc_qjd_sps_openfile.o \
		moc_qjd_sps_combinefiles.o \
		moc_qjd_sps_option.o \
		moc_qjd_sps_help.o \
		qrc_image.o
DIST          = ../../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		qjdspsshow.pro
QMAKE_TARGET  = SPSShow
DESTDIR       = 
TARGET        = SPSShow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qjd_sps_mainwindow.h ui_qjd_sps_openfile.h ui_qjd_sps_combinefiles.h ui_qjd_sps_option.h ui_qjd_sps_help.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qjdspsshow.pro  ../../qtsdk-2009.04/qt/mkspecs/linux-g++-64/qmake.conf ../../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		/home/student/qtsdk-2009.04/qt/lib/libQtGui.prl \
		/home/student/qtsdk-2009.04/qt/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qjdspsshow.pro
../../qtsdk-2009.04/qt/mkspecs/common/g++.conf:
../../qtsdk-2009.04/qt/mkspecs/common/unix.conf:
../../qtsdk-2009.04/qt/mkspecs/common/linux.conf:
../../qtsdk-2009.04/qt/mkspecs/qconfig.pri:
../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2009.04/qt/mkspecs/features/debug.prf:
../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf:
../../qtsdk-2009.04/qt/mkspecs/features/qt.prf:
../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2009.04/qt/mkspecs/features/moc.prf:
../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2009.04/qt/mkspecs/features/resources.prf:
../../qtsdk-2009.04/qt/mkspecs/features/uic.prf:
../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf:
../../qtsdk-2009.04/qt/mkspecs/features/lex.prf:
../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf:
/home/student/qtsdk-2009.04/qt/lib/libQtGui.prl:
/home/student/qtsdk-2009.04/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qjdspsshow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SPSShow1.0.0 || $(MKDIR) .tmp/SPSShow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SPSShow1.0.0/ && $(COPY_FILE) --parents qjd_sps_mainwindow.h qjd_sps_widget.h qjd_sps_openfile.h qjd_sps_combinefiles.h qjd_sps_option.h qjd_sps_help.h .tmp/SPSShow1.0.0/ && $(COPY_FILE) --parents image.qrc .tmp/SPSShow1.0.0/ && $(COPY_FILE) --parents main.cpp qjd_sps_mainwindow.cpp qjd_sps_widget.cpp qjd_sps_openfile.cpp qjd_sps_combinefiles.cpp qjd_sps_option.cpp qjd_sps_help.cpp .tmp/SPSShow1.0.0/ && $(COPY_FILE) --parents qjd_sps_mainwindow.ui qjd_sps_openfile.ui qjd_sps_combinefiles.ui qjd_sps_option.ui qjd_sps_help.ui .tmp/SPSShow1.0.0/ && $(COPY_FILE) --parents qjdspsshow_cn.ts qjsspsshow_en.ts .tmp/SPSShow1.0.0/ && (cd `dirname .tmp/SPSShow1.0.0` && $(TAR) SPSShow1.0.0.tar SPSShow1.0.0 && $(COMPRESS) SPSShow1.0.0.tar) && $(MOVE) `dirname .tmp/SPSShow1.0.0`/SPSShow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SPSShow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qjd_sps_mainwindow.cpp moc_qjd_sps_widget.cpp moc_qjd_sps_openfile.cpp moc_qjd_sps_combinefiles.cpp moc_qjd_sps_option.cpp moc_qjd_sps_help.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qjd_sps_mainwindow.cpp moc_qjd_sps_widget.cpp moc_qjd_sps_openfile.cpp moc_qjd_sps_combinefiles.cpp moc_qjd_sps_option.cpp moc_qjd_sps_help.cpp
moc_qjd_sps_mainwindow.cpp: qjd_sps_widget.h \
		qjd_sps_option.h \
		ui_qjd_sps_option.h \
		qjd_sps_openfile.h \
		ui_qjd_sps_openfile.h \
		qjd_sps_combinefiles.h \
		ui_qjd_sps_combinefiles.h \
		qjd_sps_help.h \
		ui_qjd_sps_help.h \
		qjd_sps_mainwindow.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_mainwindow.h -o moc_qjd_sps_mainwindow.cpp

moc_qjd_sps_widget.cpp: qjd_sps_option.h \
		ui_qjd_sps_option.h \
		qjd_sps_widget.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_widget.h -o moc_qjd_sps_widget.cpp

moc_qjd_sps_openfile.cpp: ui_qjd_sps_openfile.h \
		qjd_sps_openfile.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_openfile.h -o moc_qjd_sps_openfile.cpp

moc_qjd_sps_combinefiles.cpp: ui_qjd_sps_combinefiles.h \
		qjd_sps_combinefiles.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_combinefiles.h -o moc_qjd_sps_combinefiles.cpp

moc_qjd_sps_option.cpp: ui_qjd_sps_option.h \
		qjd_sps_option.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_option.h -o moc_qjd_sps_option.cpp

moc_qjd_sps_help.cpp: ui_qjd_sps_help.h \
		qjd_sps_help.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_sps_help.h -o moc_qjd_sps_help.cpp

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		image/index_5.png \
		image/wheel.png \
		image/32px-Crystal_Clear_mimetype_source_r.png \
		image/gnome-stock-gnome-run.png \
		image/s.png \
		image/Torchlight_qt.png \
		image/index_6.png \
		image/120px-Torchlight_viewmag_plus.png \
		image/Crystal_Clear_action_button_cancel.png \
		image/rightclick.png \
		image/index_0.png \
		image/Nuvola_filesystems_folder_blue_open.png \
		image/index_7.png \
		image/32px-Crystal_Clear_app_database.png \
		image/receiveline.png \
		image/wrong.png \
		image/Nuvola_filesystems_folder_grey_open.png \
		image/index_1.png \
		image/32px-Crystal_Clear_action_db_remove.png \
		image/Crystal_Clear_action_exit.png \
		image/leftclick.png \
		image/index_2.png \
		image/fang.png \
		image/sr.png \
		image/32px-Crystal_Clear_action_viewmag-.png \
		image/32px-Crystal_Clear_action_db_add.png \
		image/index_3.png \
		image/Crystal_Clear_action_decrypted.png \
		image/plus.png \
		image/index_4.png \
		image/120px-Torchlight_viewmag_minus.png \
		image/Crystal_Clear_action_reload.png \
		image/32px-Crystal_Clear_action_viewmag+.png \
		image/Torchlight_help.png \
		image/Nuvola_filesystems_folder_yellow_open.png \
		image/r.png \
		image/32px-Crystal_Clear_action_db_update.png \
		image/Crystal_Clear_action_apply.png \
		image/edit-select-all.png
	/home/student/qtsdk-2009.04/qt/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qjd_sps_mainwindow.h ui_qjd_sps_openfile.h ui_qjd_sps_combinefiles.h ui_qjd_sps_option.h ui_qjd_sps_help.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qjd_sps_mainwindow.h ui_qjd_sps_openfile.h ui_qjd_sps_combinefiles.h ui_qjd_sps_option.h ui_qjd_sps_help.h
ui_qjd_sps_mainwindow.h: qjd_sps_mainwindow.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_sps_mainwindow.ui -o ui_qjd_sps_mainwindow.h

ui_qjd_sps_openfile.h: qjd_sps_openfile.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_sps_openfile.ui -o ui_qjd_sps_openfile.h

ui_qjd_sps_combinefiles.h: qjd_sps_combinefiles.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_sps_combinefiles.ui -o ui_qjd_sps_combinefiles.h

ui_qjd_sps_option.h: qjd_sps_option.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_sps_option.ui -o ui_qjd_sps_option.h

ui_qjd_sps_help.h: qjd_sps_help.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_sps_help.ui -o ui_qjd_sps_help.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qjd_sps_mainwindow.h \
		qjd_sps_widget.h \
		qjd_sps_option.h \
		ui_qjd_sps_option.h \
		qjd_sps_openfile.h \
		ui_qjd_sps_openfile.h \
		qjd_sps_combinefiles.h \
		ui_qjd_sps_combinefiles.h \
		qjd_sps_help.h \
		ui_qjd_sps_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qjd_sps_mainwindow.o: qjd_sps_mainwindow.cpp qjd_sps_mainwindow.h \
		qjd_sps_widget.h \
		qjd_sps_option.h \
		ui_qjd_sps_option.h \
		qjd_sps_openfile.h \
		ui_qjd_sps_openfile.h \
		qjd_sps_combinefiles.h \
		ui_qjd_sps_combinefiles.h \
		qjd_sps_help.h \
		ui_qjd_sps_help.h \
		ui_qjd_sps_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_mainwindow.o qjd_sps_mainwindow.cpp

qjd_sps_widget.o: qjd_sps_widget.cpp qjd_sps_widget.h \
		qjd_sps_option.h \
		ui_qjd_sps_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_widget.o qjd_sps_widget.cpp

qjd_sps_openfile.o: qjd_sps_openfile.cpp qjd_sps_openfile.h \
		ui_qjd_sps_openfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_openfile.o qjd_sps_openfile.cpp

qjd_sps_combinefiles.o: qjd_sps_combinefiles.cpp qjd_sps_combinefiles.h \
		ui_qjd_sps_combinefiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_combinefiles.o qjd_sps_combinefiles.cpp

qjd_sps_option.o: qjd_sps_option.cpp qjd_sps_option.h \
		ui_qjd_sps_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_option.o qjd_sps_option.cpp

qjd_sps_help.o: qjd_sps_help.cpp qjd_sps_help.h \
		ui_qjd_sps_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_sps_help.o qjd_sps_help.cpp

moc_qjd_sps_mainwindow.o: moc_qjd_sps_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_mainwindow.o moc_qjd_sps_mainwindow.cpp

moc_qjd_sps_widget.o: moc_qjd_sps_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_widget.o moc_qjd_sps_widget.cpp

moc_qjd_sps_openfile.o: moc_qjd_sps_openfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_openfile.o moc_qjd_sps_openfile.cpp

moc_qjd_sps_combinefiles.o: moc_qjd_sps_combinefiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_combinefiles.o moc_qjd_sps_combinefiles.cpp

moc_qjd_sps_option.o: moc_qjd_sps_option.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_option.o moc_qjd_sps_option.cpp

moc_qjd_sps_help.o: moc_qjd_sps_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_sps_help.o moc_qjd_sps_help.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

